adevinta/vulcan-checks

- cmd/vulcan-aws-trusted-advisor/local.toml
- cmd/vulcan-dkim/local.toml
- cmd/vulcan-docker-image/local.toml
- cmd/vulcan-exposed-http-endpoint/local.toml
- cmd/vulcan-exposed-memcached/local.toml
- cmd/vulcan-exposed-services/local.toml
- cmd/vulcan-exposed-ssh/local.toml
- cmd/vulcan-host-discovery/local.toml
- cmd/vulcan-masscan/local.toml
- cmd/vulcan-nessus/local.toml
- cmd/vulcan-results-load-test/local.toml
- cmd/vulcan-sleep/local.toml
- cmd/vulcan-zap/local.toml
This PR modifies all the local.toml using the field with name "Opt"s with the name "Options" as is defined in the new version of the SDK (see https://github.com/adevinta/vulcan-check-sdk/pull/2)
Note that this PR by its own does not adapt completely the checks to the new version of the SDK.
To do so, we will also need to update the version of the sdk defined in the go.mod file after that new version is in master.
> Use Options in local.toml files

- cmd/vulcan-nessus/manifest.toml
Now it is being set directly in the vulcan-persistence config files. Check https://github.com/adevinta/vulcan-persistence/pull/6
> Remove QueueName from manifest

- cmd/vulcan-gozuul/main.go
- cmd/vulcan-gozuul/manifest.toml
Check was failing for `Hostname` and `IP` targets because the `gozuul.PasiveScan` function expects a URL (e.g. "www.adevinta.com").
Now the check can scan `WebAddress`, `Hostname`, and `IP`.
For the latest two, it converts the target to a URL using schemes and ports provided by `Options`. If no options are provided, the schemes used are `http` and `https`, while the ports are `80` and `443`.
Before calling the `gozuul` library, it checks that the URLs are reachable, otherwise it skips the call to the lib.
Test env: 3 zuul instances running in ports 8080, 8081 and 8082 (vulnerable, not vulnerable and vulnerable respectively).
```
$ vulcan-gozuul -t
WARN[2019-12-05 17:30:06] Building test agent listening on URL          URL="127.0.0.1:51497" check=vulcan-gozuul checkID= checkTypeName= …
```
> Fix vulcan-gozuul to scan Hostnames and IPs

- cmd/vulcan-tls/Dockerfile
The OpenSSL version used is already included in the cloned cipherscan repository, and because of the way cipherscan is executed we don't need to change the PATH env var.
> Simplify vulcan-tls Dockerfile to build faster

- cmd/vulcan-seekret/main.go
- cmd/vulcan-seekret/manifest.toml
Prevent overloading Github servers **by default** by only cloning the last commit if the depth option is not specified.
> Set default Seekret clone depth to 1

- cmd/vulcan-aws-trusted-advisor/main.go
- go.mod
- go.sum
This PR modifies the aws trusted advisor check in order to add a new column to the resources table generated when findings are found for an AWS account. The value for this new column will be the same for all the rows: the first alias found for the AWS account or empty if no aliases have been found.
> Add account alias in aws trusted advisor check

- cmd/vulcan-exposed-http-resources/resources.yaml
The path "/dump" has triggered a false positive for us. Since there is no "grep" (hard to do with so many different extensions, many of them compressed files), I think it may make sense to remove this specific test to avoid false positives in the future.
> Remove /dump from vulcan-exposed-http-resources

- README.md
- cmd/vulcan-prowler/Dockerfile
- cmd/vulcan-prowler/local.toml.example
- cmd/vulcan-prowler/main.go
- cmd/vulcan-prowler/manifest.toml
- cmd/vulcan-prowler/prowler.go
Add a new check that uses [prowler](https://github.com/toniblyx/prowler) to determine the compliance of an AWS account against the [CIS AWS Foundations Benchmark](https://www.cisecurity.org/benchmark/amazon_web_services/).
It needs the assume role endpoint (like `vulcan-aws-trusted-advisor`) in order to get the temporary credentials to access the target account.
By default it checks against the `Level 2` profile, but can be changed passing an option.
> Add vulcan-prowler check

- cmd/vulcan-vulners/main.go
This PR modifies the vulcan-vulnercheck so, now it creates a unique vulnerability when the same finding is found in different ports of the target. The ports where that finding has been found are added to the Details field of the vulnerability. The list of CVE's found for the same finding in different ports should be the same, but in any case the check dedupes them, so only unique CVE's are added to the resources table.
This is an example of the report generates by the check, when the finding "Multiple vulnerabilities in Apache httpd"  is found in two ports of the target (look at the details section):
```
agent.State{
Status:   "FINISHED",
Progress: 1,
Report:   report.Report{
CheckData: report.CheckData{
CheckID:          "testCheckID",
ChecktypeName:    "",
ChecktypeVersion: "",
Status: …
```
> Vulcan-vulners:Unique vulnerability per host and product found in a target

- cmd/vulcan-exposed-http-resources/resources.yaml
'dump' was recently removed (https://github.com/adevinta/vulcan-checks/pull/62), this removes 'dump/' as well.
> Remove dump/ from vulcan-exposed-http-resources

- cmd/vulcan-seekret/main.go
Filter non-ASCII and non-printable characters and replace them with `?`. The goal is to avoid mojibake and inconsistent shortening in the UI while also to prevent future encoding and decoding errors along the way.
Instead of this:
We print this:
> Filter non-printable characters

- cmd/vulcan-prowler/local.toml.example
- cmd/vulcan-prowler/main.go
- cmd/vulcan-prowler/prowler.go
This PR modifies the vulcan-prowler check to accept a security level for an account and set the CIS Level to check for depending on that level.
Concretely:
- If the security level is 0 or 1, it will execute the controls included in the CIS Level 1.
- If the security is not specified or it is 2, it will execute the controls included in the CIS Level 2.
Apart from that there are some small improvements on the resources table and in the descriptions of the vulnerabilities.
> vulcan-prowler: select group of controls according to security-level

- cmd/vulcan-prowler/main.go
- go.sum
This PR fixes two issues in the vulcan-check-prowler :
- A nil pointer dereference that was happening when no security level was specified.
- The score of a the vulnerability added when no security level was specified is now properly set to Medium.
> vulcan-prowler fix nil pointer

- cmd/vulcan-zap/Dockerfile
- cmd/vulcan-zap/main.go
- cmd/vulcan-zap/manifest.toml
- cmd/vulcan-zap/zap.go
- go.mod
- go.sum
This PR implements the following improvements to the ZAP check:
- Updates to the latest available weekly version of ZAP.
- Makes use of the new AJAX spider to better crawl single page applications.
- Supports WebAddress type assets exclusively to remove guessing the server.
- Reduce progress polling frequency to avoid spamming the persistence server.
- Fix bug where unknown CWE ID were reported as 2^32-1 overflowing the DB.
> Update ZAP check to work with most recent features

- README.md
- cmd/vulcan-github-alerts/Dockerfile
- cmd/vulcan-github-alerts/local.toml.example
- cmd/vulcan-github-alerts/main.go
- cmd/vulcan-github-alerts/manifest.toml
- go.mod
- go.sum
- vulcan-github-alerts.json
This check uses the [Github GraphQL API](https://docs.github.com/en/free-pro-team@latest/graphql/reference/objects#securityvulnerability) to retrieve [security alerts related to vulnerable dependencies](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/about-alerts-for-vulnerable-dependencies) present for a repository. The check also tries to determine the minimum version necessary for each dependency to fix all the vulnerabilities reported, since the API does not currently populate the corresponding field.
Example:
> Add vulcan-github-alerts check to report vulnerable dependencies in Github 

- cmd/vulcan-vulners/main.go
The goal of this PR is to allow users to identify what software versions were present at the time of the scan in order to, for example, quickly identify if a finding was a false positive or if the software has been updated after the scan.
> Add product, version and CPEs to Vulners details

- cmd/vulcan-exposed-http-resources/main.go
This PR improves the false positive detection mechanisms in the `vulcan-http-exposed-resources` check.
The mechanisms implemeted are:
1. Querying randomly generated resource paths to identify if the server returns false `200 OK` statuses.
2. Performing the exact same check twice to identify if the server returns `200 OK` responses inconsistently.
3. Validating if the rate at which the server responds `200 OK` to requests for exposed resources is abnormally high.
Additionally, a new informational vulnerability will be added to the report in the first case in order to keep a record of the server behaviour in the case of false negatives. All false positives are now logged in the details section and, if false positives are identified, the vulnerability is reported with the highest score among …
> Improve false positive detection mechanisms

- cmd/vulcan-exposed-http-resources/main.go
- cmd/vulcan-exposed-http-resources/resources.yaml
This PR introduces the following modifications to the vulcan-exposed-http-resources check:
- Allows to specify query strings in the paths sections of the resources.yaml file, so for instance now we can specify a resource like this:
```
- paths:
- "/somewhere?query=this"
status: 200
severity: 1.0
description: a vuln found
```
- Add a new resource that detects that the following vulnerability:  https://tanzu.vmware.com/security/cve-2020-5412
In order to reduce the odds of returning a false positive the check will try to exploit the vuln by checking if it is able to reach the "http://example.com" url from the target server.
To test the check, do the following:
1. Clone the repository: https://github.com/manelmontilla/docker-hystrix-demo
2. Inside the root dir of the repository execute: ``` …
```
> Detect an unauthenticated SSRF in Hystrix Dashboard

- cmd/vulcan-nessus/main.go
- cmd/vulcan-nessus/nessus.go
This PR modifies nessus check in order to:
- Increase the default polling interval from 30s to 5min
- Set an initial delay time before starting communication with Tenable API.
This is in order to try to mitigate spikes and overloading of Tenable API during scans.
> Increase polling interval for nessus check

- cmd/vulcan-zap/zap.go
zap `cweid` default value is `-1`.
In order to avoid integer overflow when converting from zap `alert` to vulcan report `vulnerability`, in case `cweid`  is negative or bigger than int max, we set value to `0`.
> Avoid negatives in CWEID for uint32 type

- cmd/vulcan-aws-trusted-advisor/local.toml.example
- cmd/vulcan-aws-trusted-advisor/main.go
- cmd/vulcan-aws-trusted-advisor/manifest.toml
This PR improves the logic put in place for the vulcan-aws-trusted-advisor when some of its checks are enqueued for processing so we should wait up until the defined refresh TO option polling their status to verify if they are refreshed.
Also for this purpose it modifies the default refresh timeout from 5 to 60 seconds.
> Improve AWS trusted advisor checks refreshing

- cmd/vulcan-nessus/main.go
- cmd/vulcan-nessus/nessus.go
Hi, this PR modifies the default value for the `delete scan` option from `vulcan-nessus` check. Previously, the default value was `false`. If the requester didn't specify a value for `delete`, then the check would not delete any generated scans in Nessus. Now the default value is `true`, so the check will only preserve a Nessus Scan if the requester explicitly defines the `delete` option as `false`.
> cmd/vulcan-nessus: delete nessus scans by default

- cmd/vulcan-retirejs/main.go
- cmd/vulcan-retirejs/main_test.go
This PR modifies vulcan-retirejs check to avoid panicking on purpose for unnecessary reasons during check handle execution.
Panicking in this situations for permanent errors makes vulcan-agent handle the check execution in an incorrect way, which instead of marking it as FAILED, returns the message to the queue and makes this eventually be processed `MaxRead` times by the agent with the same execution process and result for each time.
Instead, the correct behavior implemented here is to return an error from within check handle execution so the vulcan-agent can parse it correctly and set the check status to FAILED on its first execution.
> Fix counterproductive panics in retirejs

- cmd/vulcan-exposed-db/main.go
- cmd/vulcan-exposed-ftp/main.go
- cmd/vulcan-exposed-hdfs/main.go
- cmd/vulcan-exposed-http/main.go
- cmd/vulcan-exposed-router-ports/main.go
- cmd/vulcan-exposed-services/main.go
- cmd/vulcan-host-discovery/main.go
- cmd/vulcan-smtp-open-relay/main.go
- cmd/vulcan-vulners/main.go
- go.mod
- go.sum
Summary of changes:
- related to https://github.com/adevinta/vulcan-check-sdk/pull/19, change all checks using the **nmap** helper provided by the SDK to disable the progress reporting
(This PR won't build until https://github.com/adevinta/vulcan-check-sdk/pull/19 is merged first)
> Disable nmap reporting progress

- cmd/vulcan-trivy/vulcan-trivy.go
This reverts commit 302b6066b1183332a8812d4257683221d8d1e342.
The reason for the revert is that we need to rewrite the summary in the issues table of the Vulnerability DB or otherwise teams will be reported duplicated findings with the issue with the new summary and with the old one. We will find a good time to do the rewrite when no scans are running.
> Revert "Remove beta status from Trivy check (#96)"

- cmd/vulcan-retirejs/main.go
This PR fixes vulcan-retirejs check execution, more specifically the arguments used to call the underlying NPM _retire_ command.
> Fix retirejs cmd execution args

- cmd/vulcan-s3-takeover/main.go
Currently the vulnerability doesn't reflect how actually the information was found and the name of the missing bucket. This PR adds that information inside the vulnerabilty.Details field so the user can understand and reproduce the issue.
> Include details of the non-existent bucket in s3 subdomain takeover vulnerability

- cmd/vulcan-zap/manifest.toml
This PR modifies the vulcan-zap in order
to disable checking for the reverse [tabnabbing alert](https://www.zaproxy.org/docs/alerts/10108/)
Example, taken from https://owasp.org/www-community/attacks/Reverse_Tabnabbing, of an html that triggers that zap alert:
```HTML
<html>
<body>
<li><a href="http://bad.example.com" target="_blank">Vulnerable target using html link to open the new page</a></li>
<button onclick="window.open('https://bad.example.com')">Vulnerable target using javascript to open the new page</button>
</body>
</html>
```
Report of the vulnerabilities generated by the check when it's run against a page containing the previous html and before applying the modifications:
Report of the vulnerabilities generated by the check when run against a page containing the previous html …
> vulcan-zap: disable reverse-tabnabbing

- cmd/vulcan-masscan/Dockerfile
**Summary:**
In recent versions of Alpine, the syscall `faccessat2` has been added to musl which causes problems in the presence of `libseccomp` on the docker host when compiling with `gcc` . This issue makes our builds fail in Travis' workers.
This PR pins Alpine to the latest available version that is not affected by the issue.
**Example of the issue ([link](https://app.travis-ci.com/github/adevinta/vulcan-checks/builds/237173786#L1225-L1233)):**
```
Step 5/8 : RUN make -j
---> Running in f6d96ad4c327
make: cc: Operation not permitted
make: git: Operation not permitted
make: cc: Operation not permitted
make: *** [Makefile:109: tmp/crypto-base64.o] Error 127
cc -g -ggdb    -Wall -O2 -c src/crypto-base64.c -o tmp/crypto-base64.o
The command '/bin/sh -c make -j' returned a non-zero code: 2 …
```
> Pin masscan alpine version to 3.13.6: avoid usage of faccessat2 syscall

- cmd/vulcan-drupal/vulnerabilities.go
Version 7 of drupal isn't vulnerable to this bug, only some specific plugins, so this generates a false positive for us.
I think that if we want to do detection checking for this bug on version 7, we need to either detect the version of those plugins or maybe try to automate a direct detection of the specific bug.
> Removed the 7 to 8 version config for SA-CORE-2019-003

- cmd/vulcan-trivy/Dockerfile
- cmd/vulcan-trivy/vulcan-trivy.go
Upgrade to a newer version of Trivy.
This new version detects CVE-2021-44228
> Upgrade trivy

- cmd/vulcan-seekret/main.go
- cmd/vulcan-seekret/manifest.toml
- Removes default master branch. To allow the check to use the default ref served by the git server (master, main , ...)
- Use a fixed path for the repo, preventing the issue when the git url doesn't have a path (i.e. http://localhost:port/)
> Remove default branch in seekret

- cmd/vulcan-zap/main.go
This PR fixes the context misuse.
In fact, the context is created at the beginning of the process but is not passed to the spider actions nor to the scan action and therefore the only URL/Path scanned were the ones resolved by the [recurse option](https://www.zaproxy.org/docs/api/#ascanactionscan) and the target URL provided.
I would appreciate a careful review on the changes.
> Use created context in spider and scan

- cmd/vulcan-zap/main.go
- cmd/vulcan-zap/zap.go
This PR includes 2 main changes:
- Context was created but not passed to the spider neither to the scan process. By passing the context to the spider and the scan processes we ensure the scan reaches the deepness specified by the check options.
- Added labels to improve filtering in the UI and fingerprint to findings to provide more accurate actions on the finding (mainly mark as false positive).
> Add context, labels and fingerprint to ZAP

- cmd/vulcan-retirejs/main.go
- cmd/vulcan-retirejs/main_test.go
- cmd/vulcan-retirejs/manifest.toml
This PR includes the following changes:
- It now accept Hostname andWebAddress as target asset types. Before only Hostnames were accepted.
- Aggregating vulnerabilities for the same affected resource and generating a proper fingerprint (in the same way Github Alerts and Trivy checks are doing).
- Some changes done in how retire command runs and how to parse the results in order to workaround [retire.js issue 356](https://github.com/RetireJS/retire.js/issues/356).
> Migrate vulcan-retirejs check to v2

- cmd/vulcan-zap/main.go
- cmd/vulcan-zap/manifest.toml
Add new options for Vulcan-zap:
- max_spider_duration: Applies to both normal an Ajax spiders.
- max_scan_duration: Limits the total amount of time spent in all the rules.
- max_rule_duration: Limits the time spent in one rule.
- openapi_url: Allows to specify a Openapi/swagger url.
- openapi_host: Used with the previous one.
> Add additional zap options

- cmd/vulcan-heartbleed/main.go
* Labels the finding as issue
* Uses port 443/tcp as affected resource
* Uses an empty fingerprint
Execution example:
```
...
ResultData: report.ResultData{
Vulnerabilities: {
{
ID:                     "",
Summary:                "Heartbleed",
Score:                  8.899999618530273,
AffectedResource:       "443/tcp",
AffectedResourceString: "",
Fingerprint:            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
CWEID:                  0x77,
Description:            "OpenSSL versions 1.0.1 through 1.0.1f contain a flaw in its implementation of the TLS/DTLS heartbeat functionality.This flaw allows an attacker to retrieve private memory of an application that uses the vulnerable OpenSSL library in chunks of  64k at a time. Note that an attacker can repeatedly …
```
> Migrate vulcan-heartbleed to v2

- cmd/vulcan-host-discovery/main.go
- Discovered hosts are now splitted in different vulnerabilities.
- The affected resource is the discovered host IP.
- The fingerprint is computed using the host IP and hostname.
- Vulnerabilities are labeled as "issue" and "discovery".
> Migrate vulcan-host-discovery to v2

- cmd/vulcan-s3-takeover/local.toml.example
- cmd/vulcan-s3-takeover/main.go
- cmd/vulcan-s3-takeover/manifest.toml
Modifications conducted:
* The check now can be used against `Hostname` or `WebAddress`
* For the case of a `Hostname`, both `http` and `https` are tested
* The affected resource is the resolved target (i.e. the target itself in case of `WebAddress` and the generated `http` and `https` URLs for `Hostname`)
* The findings are labeled as `issue`
* The bucket name is used to calculate the fingerprint
To test a `Hostname` use `${RANDOM_NAME}.s3-website-eu-west-1.amazonaws.com` as the target.
To test a `WebAddres` use `http://${RANDOM_NAME}.s3-website-eu-west-1.amazonaws.com` as the target.
To test the `https` and/or the `application/xml` flows, you can create a CloudFront distribution pointing to a S3 static web-hosting. I have one created to show the behaviour during the code review.
> Migrate vulcan-s3-takeover to v2

- cmd/vulcan-exposed-ftp/main.go
- Expands the Exposed FTP vulnerability's resources table into individual vulnerabilities, so they can be individually actioned
- Calculates the fingerprint of each vulnerability so actions applied to them can be dismissed if the context changes
- Adds labels to the vulnerabilities
> Expand vulcan-exposed-ftp vulnerabilities and add labels

- cmd/vulcan-exposed-rdp/main.go
- Adapt to the affected resources model
- Calculates the fingerprint of each vulnerability so actions applied to them can be dismissed if the context changes
- Adds labels to the vulnerabilities
> Expand vulcan-exposed-rdp vulnerabilities and add labels

- cmd/vulcan-exposed-db/main.go
- Expands the Exposed DB vulnerability's resources table into individual vulnerabilities, so they can be individually actioned
- Calculates the fingerprint of each vulnerability so actions applied to them can be dismissed if the context changes
- Adds labels to the vulnerabilities
> Expand vulcan-exposed-db vulnerabilities and add labels

- cmd/vulcan-semgrep/semgrep.go
The field metadata.owasp can be a string or []string and this can be create a unmarshall error. I comment the field for solve this given that the field is not used.
Thanks!
> semgrep owasp field comment

- cmd/vulcan-wpscan/main.go
- cmd/vulcan-wpscan/wpscan.go
This PR tries to improve several aspects of the execution of WPScan command.
- Specified a custom HTTP user-agent.
- Add `--ignore-main-redirect` param if the target redirects to a site contains any matching pattern specified in `ignoreMainRedirect`.
- In the case WPScan is aborted due to WAF user-agent header detection, we are trying again with `--random-user-agent` parameter as is recommended by the tool.
- WPScan cli tool exit code is now being taken into count for the result.
> Improve WPScan execution behaviour

- cmd/vulcan-burp/burp.go
- cmd/vulcan-dmarc/dmarc_vulnerabilities.go
- cmd/vulcan-exposed-bgp/main.go
- cmd/vulcan-exposed-hdfs/main.go
- cmd/vulcan-exposed-http-resources/main.go
- cmd/vulcan-exposed-http/main.go
- cmd/vulcan-exposed-router-ports/main.go
- cmd/vulcan-exposed-varnish/main.go
- cmd/vulcan-http-headers/main.go
- cmd/vulcan-http-headers/vulnerabilities.go
- cmd/vulcan-ipv6/main.go
- cmd/vulcan-masscan/main.go
- cmd/vulcan-mx/main.go
- cmd/vulcan-nessus/nessus.go
- cmd/vulcan-nuclei/main.go
- cmd/vulcan-prowler/main.go
- cmd/vulcan-spf/spf_vulnerabilities.go
- cmd/vulcan-unclassified/main.go
- cmd/vulcan-wpscan/main.go
- cmd/vulcan-zap/zap.go
The fact that the same vulnerability might have different labels per execution was introducing some unexpected behaviours, as the labels are defined at _issue_ level in the Vulnerability DB model. This was particularly triggered in those cases where the same issue might have a score 0 or different from 0 depending on the execution.
It was discussed an agreed to not label vulnerabilities as `informational` when the score is 0. We will label them with the exact same labels than when the score is different from 0. Even more, labels shouldn't change during runtime, as they shouldn't include runtime information.
> bugfix: remove informational label from all checks

- cmd/vulcan-zap/main.go
- cmd/vulcan-zap/manifest.toml
- cmd/vulcan-zap/zap.go
This PR adds a new supported option for `vulcan-zap` check which allows to define a list of Zap proxy plugin IDs for which the resources associated with the vulnerabilities reported by them will not be taken into account for the fingerprint generation.
The reason for this functionality is to try to mitigate the variability of the fingerprint for some type of vulnerabilities, especially the injection type ones like SQLi, which eventually does not allow Vulcan end users to mark a finding as _false positive_ permanently, as the finding is recurrently being reopened due to the variations on the associated resources, for example the payload used for the attack.
> Support configure ignored scanners for fingerprint generation

- cmd/vulcan-exposed-http-resources/resources.yaml
When Laravel is in debug mode it generates a 404 page showing the source code of the exception
```php
$kernel = new AppKernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$request = Request::createFromGlobals();
$response = $kernel->handle($request);$response->send();
```
Another option could be to remove APP_ENV from the regex
> Force status 200 for Laravel

- cmd/vulcan-gitleaks/Dockerfile
The base image contains labels not compatible with jfrog artifactory (it complains with `manifest invalid: manifest invalid`)
```sh
docker inspect zricethezav/gitleaks | jq '.[].Config.Labels'
{
"org.opencontainers.image.created": "2022-06-20T20:12:37.413Z",
"org.opencontainers.image.description": "Protect and discover secrets using Gitleaks 🔑",
"org.opencontainers.image.licenses": "MIT",
"org.opencontainers.image.revision": "70028079b4c47e0dd2e1ed116aeaeeac23ef0c1d",
"org.opencontainers.image.source": "https://github.com/zricethezav/gitleaks",
"org.opencontainers.image.title": "gitleaks",
"org.opencontainers.image.url": "https://github.com/zricethezav/gitleaks",
"org.opencontainers.image.version": "v8.8.8"
}
```
This PR replaces that label.
NOTE: An improvement out of the scope of this …
> Fix GitLeaks label not supported by artifactory

- cmd/vulcan-wpscan/main.go
By default WPScan returns all existing issues associated with a plugin when its version cannot be identified, leading to a very large number of false positives when this happens. This PR eliminates this behavior and adds additional details related with the detection confidence of plugins and their versions.
> Ignore issues for plugins with unknown version

- cmd/vulcan-prowler/main.go
- cmd/vulcan-prowler/prowler.go
This PR modifies vulcan-prowler implementation in order to fix the `region` option handling.
Previously the `region` option parameter available to configure the check, was set as value for the Prowler `-r` parameter. If we take a look at the Prowler documentation we can see:
```
Prowler has two parameters related to regions: -r that is used query AWS services API endpoints (it uses us-east-1 by default and required for GovCloud or China) and the option -f that is to filter those regions you only want to scan. For example if you want to scan Dublin only use -f eu-west-1 and if you want to scan Dublin and Ohio -f eu-west-1,us-east-1, note the regions are separated by a comma deliminator (it can be used as before with -f 'eu-west-1,us-east-1').
```
Therefore, our previous usage of the `-r` …
> vulcan-prowler: Fix region option handling

- cmd/vulcan-http-headers/main.go
As X-XSS-Protection header is deprecated and no longer recommended, I think it should be removed from this check. This change only make it ignore X-XSS-Protection findings, and does not change [the struct](https://github.com/adevinta/vulcan-checks/blob/master/cmd/vulcan-http-headers/observatory.go#L126-L133) `observatoryResult`.
> Remove X-XSS-Protection findings

- cmd/vulcan-gitleaks/main.go
- go.mod
Change severity to 8.9 to be a real HIGH and solve the problem that bcrypt algorithm generates a different hash in every execution because the salt is random generated.
> solve severity and hash problem in gitleaks check

- cmd/vulcan-http-headers/Dockerfile
Debian stretch is out of support on 2022-06-30, https://wiki.debian.org/DebianReleases
Also updated http-observability to version 0.9.3, https://github.com/mozilla/http-observatory
> Debian stretch is out of support on 2022-06-30

- cmd/vulcan-exposed-files/main.go
Detect exposed heap dump issue in improperly configured Spring Boot.
Modifies the check to limit reading the response to a certain number of bytes to avoid downloading very large files in full.
Improve description and recommendations to be relevant to most possible findings.
Raise severity of exposed environment variables to high.
> Exposed heap dump file and relevant improvements

- cmd/vulcan-exposed-http-resources/resources.yaml
A new medium vulnerability has been added for exposed authenticated Apache Airflow administration panels and a critical severity one has been added for panels that require no authentication and potentially allow data queries and code execution.
> Detect exposed Apache Airflow admin panels

- release.sh
By pushing the check tags when building master greatly increases the chances when a new branch is created no docker image needs to be build unless a change has been made.
> Generate check tags to improve cache hit

- cmd/vulcan-trivy/Dockerfile
- cmd/vulcan-trivy/local.toml.example
- cmd/vulcan-trivy/manifest.toml
- cmd/vulcan-trivy/vulcan-trivy.go
- Add GitRepository as an asset type.
- Bumps aquasec/trivy to `0.32.1`
- Added Title to the resource table with a short vulnerability description for both docker/git.
- No secret scanning activated (`--security-checks vuln`) already done with GitLeaks check.
- Activated for  GitRepository (not in DockerImage as it's very unusual to find config files inside a Dockerimage).
- Reference `.trivyignore` in details on how to ignore trivy findings.
- Uses the severity provided by trivy.
> Trivy add git

- cmd/vulcan-exposed-files/main.go
This PR resolves a couple of issues with the exposed files check:
- The references are issue-level and shown for all findings so should not contain any custom data.
- The quotes were double escaped and the backslashes were displayed in the UI.
This check may be further improved by merging all vulnerabilities into one with several resources listed in the resources table as other checks do. However, I have chosen not to do that since this check may soon either be deprecated (in favor of Nuclei) or merged with the exposed HTTP resources check which is very similar.
> Fix incorrect use of references and quote encoding

- cmd/vulcan-tls/main.go
The check relies on `openssl` binaries from https://github.com/mozilla/cipherscan, old version and only available for Darwin or amd64 (not arm64)
This pr forces the use of the openssl version in `python:3.7-slim`
Upgrades the pretty old openssl version
```sh
OpenSSL 1.0.2-chacha (1.0.2i-dev)
OpenSSL 1.1.1n  15 Mar 2022
```
> Use container openssl available in all architectures

- cmd/vulcan-trivy/manifest.toml
Set trivy checks timeout.
If not specified Vulcan-agent defaults to what's configured and in the case of trivy that default could be too much restrictive provided the timeout includes the pull time.
> Set trivy timeout

- cmd/vulcan-nuclei/Dockerfile
- cmd/vulcan-nuclei/main.go
- cmd/vulcan-nuclei/manifest.toml
This PR fixes an error with a [deprecated Nuclei flag](https://github.com/projectdiscovery/nuclei/pull/2962), pins the current version to avoid future breakages and enables a limited list of conservative templates so that the check can be included in the default Vulcan policy. Further templates can be included in more aggressive policies or for specific assets by adding them through options or removing the whitelist option altogether.
> Fix Nuclei flag error and set conservative templates

- cmd/vulcan-nuclei/nuclei.go
Fixes this error: `cannot unmarshal bool into Go struct field Info.info.metadata of type string`
```json
{
"template": "technologies/pypiserver-detect.yaml",
"template-url": "https://github.com/projectdiscovery/nuclei-templates/blob/master/technologies/pypiserver-detect.yaml",
"template-id": "pypiserver-detect",
"info": {
"name": "PyPI Server Detect",
"author": [
"ritikchaddha"
],
"tags": [
"tech",
"pypiserver"
],
"reference": null,
"severity": "info",
"metadata": {
"verified": true,
"shodan-query": "html:\"pypiserver\""
}
},
"type": "http",
"host": "https://www.google.com/",
"matched-at": "https://www.google.com/",
"ip": "142.250.184.164",
"timestamp": "2022-12-15T17:33:13.249765+01:00",
"curl-command": "curl -X 'GET' -d '' -H 'Accept: */*' -H 'Accept-Language: en' -H 'User-Agent: …
```
> Fix unmarshall error

- cmd/vulcan-github-alerts/main.go
Vulcan is reporting previously reported vulnerabilities detected by Github as open when in fact they have been fixed or dismissed. This happens because the Github GraphQL API returns all existing and previous vulnerabilities regardless of current status. This issue is fixed by explicitly verifying that the current status of the vulnerability is "OPEN". This requires pulling the additional "[RepositoryVulnerabilityAlertState](https://docs.github.com/en/graphql/reference/enums#repositoryvulnerabilityalertstate)" attribute from GraphQL and checking it reporting a vulnerability.
Additionally, the "[FirstPatchedVersion](https://docs.github.com/es/graphql/reference/objects#securityadvisorypackageversion)" attribute was being parsed as a string instead of an struct due to it being missing from …
> Correctly parse Github Alerts GraphQL output

- cmd/vulcan-retirejs/Dockerfile
- cmd/vulcan-retirejs/main.go
- fix retire error traversing /
```sh
Exception caught: Error: ENOENT: no such file or directory, lstat '/proc/1/ns/cgroup:[4026533078]'
at Object.realpathSync (node:fs:2588:7)
```
- Remove deprecated parameter --json
- Show errOutput on ParseError to help diagnose problems
> fix retirejs

- cmd/vulcan-retirejs/Dockerfile
The build process failed with yarn in arm64.
```
> [linux/arm64 3/5] RUN yarn global add retire:
#16 3.513 yarn global v1.22.19
#16 4.293 [1/4] Resolving packages...
#16 9.938 error Couldn't find package "pac-proxy-agent@^5.0.0" required by "proxy-agent@^5.0.0" on the "npm" registry.
#16 9.941 info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
------
Dockerfile:5
--------------------
3 |     FROM node:alpine
4 |     RUN apk add --no-cache ca-certificates
5 | >>> RUN yarn global add retire
6 |     ADD https://raw.githubusercontent.com/RetireJS/retire.js/master/repository/jsrepository.json /jsrepository.json
7 |     ARG TARGETOS TARGETARCH
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn global add retire" did not complete …
```
> Fix retirejs install with yarn arm64

- cmd/vulcan-trivy/Dockerfile
- cmd/vulcan-trivy/config/secret.yaml
- cmd/vulcan-trivy/local.toml.example
- cmd/vulcan-trivy/manifest.toml
- cmd/vulcan-trivy/vulcan-trivy.go
This pull request adds support for scanning GitRepository assets for secrets using Trivy secret scanning feature. The following changes have been made:
- GitRepository asset type is now included as a target for the secret scanning check. This requires the inclusion of the environment variables `GITHUB_ENTERPRISE_ENDPOINT` and `GITHUB_ENTERPRISE_TOKEN`.
- Secret scanning is enabled only for GitRepository assets and not for Docker images.
- Secret scanning is performed with a custom Trivy configuration file by default to reduce false positives.
> Enable secret scanning for GitRepository asset type

- cmd/vulcan-http-headers/Dockerfile
Fixes check not working in python 3.11, need to downgrade to 3.9 for celery
```sh
vulcan-local -t example.com -i http-headers -l DEBUG
...
ImportError: cannot import name 'Callable' from 'collections'
```
Also the alpine based image has almost any vulns.
> Fix http-headers check

- cmd/vulcan-retirejs/main.go
- cmd/vulcan-retirejs/main_test.go
We have detected that `vulcan-retirejs` was failing under some circumstances:
1. While scanning sites with non-valid SSL certificates (expired, self-signed, etc.) (fixed in ffd74f6dc6e62c5dc721fd43e770fe8b9dd9012a)
2. When imported Javascript dependencies had several parameters (fixed in 37e082657ef6d822be1fcca6f68dbc224301e0fd)
This PR addresses those errors.
> Prevent vulcan-retirejs failing under some circumstances

- .travis.yml
Semgrep released an arm64 image, so we can build our vulcan-semgrep arm64 check.
> Remove semgrep from arm blacklist

- cmd/vulcan-trivy/config/secret.yaml
- cmd/vulcan-trivy/local.toml.example
- cmd/vulcan-trivy/manifest.toml
- cmd/vulcan-trivy/vulcan-trivy.go
This PR modifies `vulcan-trivy` to enable docker image secret scanning, including the image metadata, and adds a rule to detect JFrog Artifactory credentials ported from Gitleaks.
> Enable Docker image secret scanning for Trivy

- cmd/vulcan-trivy/entrypoint.sh
- cmd/vulcan-trivy/vulcan-trivy.go
The Trivy CLI returns execution errors as log entries in STDERR even when the json output format is used. In fact the Trivy report data structure does not contain any field to store errors. That makes very hard to capture and process the Trivy CLI errors to be embedded in the 'check.Report.Error' attribute.
This commit tries to improve the situation by applying this changes:
- Reduce the output the Trivy CLI generates just to errors
- Ensure the error returned by the Trivy CLI is the one embedded in the 'check.Report.Error' attribute
- In case of Trivy CLI retries, make the check to log all of them but return just the last one
- Add an error tag to the check logs to make easier to filter logs by them. For example to filter logs by "retry trivy command execution failed"
> vulcan-trivy.go: improve Trivy CLI errors capture

- .github/dependabot.yml
- cmd/vulcan-zap/Dockerfile
- cmd/vulcan-zap/main.go
- cmd/vulcan-zap/manifest.toml
- go.mod
- go.sum
- Improve speed/disk by disabling db recovery log (not a game changer)
See <https://groups.google.com/g/zaproxy-users/c/L51nDFh0fjk>
- Ugrade github.com/zaproxy/zap-api-go
- Pin [2.13.0](https://www.zaproxy.org/blog/2023-07-12-zap-2.13.0/) and add to dependabot.
- Fix 2.13.0 not working because of add-on updates after server is suposed to be ready.
```
level=warning msg="Scan not present in response body when calling Spider().Scan()" checkID=9f514c48-5d09-11ee-8109-465c9e98cb60"
```
- Add optimizations from [`zap_tune`](https://github.com/zaproxy/zaproxy/blob/5dd9a9f5c836d6c1e905265e3adc3e3c07d37467/docker/zap_common.py#L402)
- Setup max_scan_duration to allow the scan to report vulnerabilities before being killed by the agent.
> Fix and improve zap

- cmd/vulcan-nuclei/local.toml.example
- cmd/vulcan-nuclei/manifest.toml
This PR enables IP AssetType scanning for vulcan-nuclei check.
For more detail visit internal discussion # 44.
> Enable IP AssetType scanning for vulcan-nuclei check

- cmd/vulcan-trivy/vulcan-trivy.go
As discused in
https://github.com/adevinta/vulcan-checks/pull/464#discussion_r1348614181
remove the retries to avoid repeating several times idempotent errors.
> cmd/vulcan-trivy: remove retries for trivyCmd

- cmd/vulcan-gitleaks/Dockerfile
The user 'gitleaks' was removed in this commit upstream: https://github.com/gitleaks/gitleaks/commit/ac4b5146b0f112df989b4374abb2b12799e37cba
When building this check now, it will fail with the error:
```
unable to convert uid/gid chown string to host mapping
```
Removing this argument pointing to a user that does not exists should fix the issue.
> Remove '--chown' from COPY instruction, as user no longer exists

- cmd/vulcan-trivy/Dockerfile
change repos to use AWS ecr aqauasecurity, because ghcr needs authented to download db and java-db containers
> Update trivy-check Dockerfile [ change container registry source for images ] 

- .github/workflows/release.yml
All the dependabot builds were failing because the DKR_PASSWORD secret was not available. I fixed this by adding the secret as a DEPENDABOT secret.
With that setup in place we don't need the pull_request event as right now we are not accepting PR other than dependabot ones (and dependabot PRs triggers a push event). So we can save resources and time.
- A pr from a team member or dependabot will generate a push.
- A pr from others won't have access to the DKR_PASSWORD and would fail.
Other better solution would be to design the action to be able to build everything without pushing.
It would be important to keep the whole build process on all the architectures -as there could be issues based on the architecture- but  docker buildx doesn't allow to just build without pushing.
> Remove pull_request trigger

- cmd/vulcan-trivy/vulcan-trivy.go
- Uses a local logger
- Fixes panic when trivy fails
- Uses sdk helper/command
- Prevent leaked directories/files
- Skip big non-binary files when secret analysis is activated.
- Other refactors.
> Improve and fix vulcan-trivy

- cmd/vulcan-aws-subdomain-takeover/local.toml.example
- cmd/vulcan-aws-subdomain-takeover/main.go
The curly brackets can cause problems when storing the configuration in some systems as AWS. So, the variable INVENTORY_ENDPOINT, which represents a Go template, will be passed encoded in base64.
> encode the INVENTORY_ENDPOINT variable in base64

- cmd/vulcan-repository-sctrl/github.go
- cmd/vulcan-repository-sctrl/main.go
Change the endpoint to verify if Dependabot (automatic security fixes) is enabled and remove GHAS controls.
> ghe-reposec: change dependabot check
