- cmd/vulcan-tls/main.go
> Do not fail when testing connection in vulcan-tls

- go.mod
- go.sum
https://github.com/adevinta/gozuul/pull/1
> Update gozuul dependency

- cmd/vulcan-wpscan/Dockerfile
- cmd/vulcan-wpscan/main.go
- cmd/vulcan-wpscan/manifest.toml
- cmd/vulcan-wpscan/wpscan.go
Also fix [a bug](https://jira.mpi-internal.com/browse/PTVUL-1648) and simplify the docker image.
> Add required WPVulnDB API token to vulcan-wpscan

- cmd/vulcan-vulners/.gitignore
- cmd/vulcan-vulners/Dockerfile
- cmd/vulcan-vulners/local.toml.example
- cmd/vulcan-vulners/main.go
- cmd/vulcan-vulners/manifest.toml
Based on Nmap NSE [vulners script](https://github.com/vulnersCom/nmap-vulners) that correlates vulnerabilities in the [NVD](https://nvd.nist.gov/) with the services detected by Nmap.
Tested against Metasploitable:
> Add vulcan-vulners check

- cmd/vulcan-s3-takeover/main.go
```
$ nmap -p 80 X.X.X.X
Starting Nmap 7.80 ( https://nmap.org ) at 2020-02-04 11:09 CET
Nmap scan report for X.X.X.X (Y.Y.Y.Y)
Host is up (0.052s latency).
Other addresses for X.X.X.X (not scanned): W.W.W.W Z.Z.Z.Z
PORT   STATE    SERVICE
80/tcp filtered http
Nmap done: 1 IP address (1 host up) scanned in 0.69 seconds
```
```
$ vulcan-s3-takeover -t
WARN[2020-02-04 11:11:27] Building test agent listening on URL          URL="127.0.0.1:60241" check=vulcan-s3-takeover checkID= checkTypeName= checkTypeVersion= component=check opts= target=X.X.X.X
INFO[2020-02-04 11:11:27] Check start                                   check=vulcan-s3-takeover checkID= checkTypeName= checkTypeVersion= component=check opts= target=X.X.X.X
INFO[2020-02-04 11:11:30] Check finished …
```
> Avoid failing s3-takeover check by timeout

- cmd/vulcan-retirejs/main.go
And check for HTTPS targets too.
> Fix timeout and certificate errors in retirejs

- cmd/vulcan-trivy/go.mod
- cmd/vulcan-trivy/go.sum
- go.mod
- go.sum
This PR updates the the references to the sdk to the last version.
> Update vulcan-sdk version

- go.mod
- go.sum
vulcan-nessus: Fix a panic condition found when performing requests agains the remote API
> Update Restuss to latest version

- .travis.yml
- _scripts/libdocker.sh
- _scripts/libgit.sh
- release.sh
Build checks, docker images and push them to Docker Hub:
https://hub.docker.com/u/vulcansec
> Build and push

- cmd/vulcan-trivy/vulcan-trivy.go
`results` contains something like this when there aren't vulns:
```
[
{
"Target": "registry/image:tag (alpine 3.10.3)",
"Vulnerabilities": null
}
]
```
**Target with vulns:**
```
agent.State{
Status:   "FINISHED",
Progress: 1,
Report:   report.Report{
CheckData: report.CheckData{
CheckID:          "testCheckID",
ChecktypeName:    "",
ChecktypeVersion: "",
Status:           "FINISHED",
Target:           "REDACTED-vulnerable",
Options:          "",
Tag:              "",
StartTime:        time.Time{},
EndTime:          time.Time{},
},
ResultData: report.ResultData{
Vulnerabilities: {
{
ID:              "",
Summary:         "Outdated Packages in Docker Image (BETA)",
Score:           6.900000095367432,
CWEID:           0x3a9,
Description:     "Vulnerabilities have been found in outdated …
```
> Fix vulcan-trivy to not report empty vulns

- cmd/vulcan-exposed-http-resources/main.go
Completely remove low and medium confidence resources that were found under dubious conditions from the resources table. If the resulting vulnerability presents no vulnerable resources after removing the dubious ones, do not report the vulnerability.
The goal of this change is to avoid noise in the resources table that could potentially hide true positives.
> Remove HTTP resources that are false positive

- README.md
Added a small section on how to build and test the checks locally,
> Added a section about building and testing to the readme

- cmd/vulcan-trivy/vulcan-trivy.go
Currently all the findings will have the same fingerprint, but it would be better instead that each finding had its own fingerprint based on the CVEs for its affected resource.
> Calculate fingerprint per affected resource

- cmd/vulcan-tls/main.go
- cmd/vulcan-tls/vulnerabilities.go
* Each failure detected by cipherscan will be reported as a separated Vulnerability
* The fingerprint takes into account contextual things that may change
* All the vulnerabilities will be labeled as issues
> Expand tls resources into different findings

- cmd/vulcan-dmarc/dmarc.go
- cmd/vulcan-dmarc/dmarc_vulnerabilities.go
- cmd/vulcan-dmarc/main.go
* Vulnerabilities are labeled as issues, except those that are
infomational
* The affected resource is the target itself
* Default fingerprint provided
> Migrate vulcan-dmarc to v2

- cmd/vulcan-spf/main.go
- cmd/vulcan-spf/spf.go
- cmd/vulcan-spf/spf_vulnerabilities.go
* Vulnerabilities are labeled as issues, except those that are informational
* The affected resource is the target itself
* Default fingerprint provided
> Migrate vulcan-spf to v2

- cmd/vulcan-exposed-http/main.go
- Create an issue per exposed port
- The affected resource is the host:part
- Labeled as `issue` and protocolo (i.e. `tcp`)
> Migrate exposed-http to v2

- cmd/vulcan-semgrep/.gitignore
- cmd/vulcan-semgrep/local.toml.example
- cmd/vulcan-semgrep/main.go
- cmd/vulcan-semgrep/manifest.toml
- Allow to set the branch to analyse
- Use system temp path
- Fix depth option name
- Ensure apply of default options
> Improve semgrep

- cmd/vulcan-exposed-amt/local.toml.example
- cmd/vulcan-exposed-amt/main.go
* The port will be used as the affected resource
* Is being labelled as issue
* Fingerprint is calculated with no args
> Migrate vulcan-exposed-amt to v2

- cmd/vulcan-exposed-bgp/main.go
* Change some attributes of the vulnerability
* Use the port as the affected resource
* Labelled as informational
* Computing a fingerprint without args
> Migrate vulcan-exposed-bgp to v2

- cmd/vulcan-mx/main.go
* Small refactor of the check
* Use the target as affected resource
* Labelled as informational
* Using a fingerprint with no args
> Migrate vulcan-mx to v2

- cmd/vulcan-smtp-open-relay/main.go
Expand resources into vulnerabilities
Validated against:
```sh
docker run -p 587:25 -p 25:25 -d -e POSTFIX_myhostname=smtp.domain.tld mwader/postfix-relay
```
> Expand smtp-open-relay resources into vulns

- cmd/vulcan-exposed-router-ports/main.go
- Change some attributes of the vulnerability
- Use the port / protocol as the affected resource
- Labelled as informational
- Computing a fingerprint with service.program
> Expand exposed-router-ports resources into vulns

- cmd/vulcan-exposed-services/main.go
- Expands each exposed service into an its own vulnerability so it can be individually actioned.
- Calculates the fingerprint of each vulnerability so actions applied to them can be dismissed if the context changes.
- Adds labels to the vulnerabilities.
Almost identical to #143.
> Migrate vulcan-exposed-services to v2 

- cmd/vulcan-seekret/main.go
- Add the `target` as Affected Resource.
- Add Labels `"issue"` and `"potential"`.
- Compute Fingerprint from a sorted list of files and matches found.
> Migrate vulcan-seekret to v2

- cmd/vulcan-ipv6/main.go
* Small refactor of the check
* Use the target as affected resource
* Labelled as informational
* Using a fingerprint with no args
> Migrate vulcan-ipv6 to v2

- cmd/vulcan-masscan/main.go
* Expand each open port to a different finding
* Labelled as informational
* Computing a fingerprint with no args
> Migrate vulcan-masscan to v2

- cmd/vulcan-lucky/main.go
> Update vulcan-lucky to v2

- README.md
- cmd/vulcan-nuclei/.gitignore
- cmd/vulcan-nuclei/Dockerfile
- cmd/vulcan-nuclei/local.toml.example
- cmd/vulcan-nuclei/main.go
- cmd/vulcan-nuclei/manifest.toml
- cmd/vulcan-nuclei/nuclei.go
This PR adds vulcan-nuclei check integration.
The check runs [Nuclei](https://github.com/projectdiscovery/nuclei) scanner tool with selected [templates](https://github.com/projectdiscovery/nuclei-templates/).
> Add vulcan-nuclei check

- .travis.yml
- pages/index.html
Publish master checktypes in gh-pages:
- https://adevinta.github.io/vulcan-checks/
- https://adevinta.github.io/vulcan-checks/checktypes/edge.json
> Publish checks catalog for master in gh-pages

- README.md
- cmd/vulcan-gitleaks/README.md
- cmd/vulcan-semgrep/README.md
- cmd/vulcan-trivy/README.md
Added very basic docs vulcan-gitleaks, vulcan-semgrep and vulcan-trivy checks.
> added basic docs in some checks

- cmd/vulcan-gitleaks/main.go
added internal ip to localTargets
> added internal ip to localTargets

- cmd/vulcan-semgrep/Dockerfile
- cmd/vulcan-semgrep/main.go
- cmd/vulcan-semgrep/semgrep.go
- go.mod
- Fix Unmarshal adding support for slices in cwe
- Pin semgrep 0.116.0
- Use helpers.CloneGitRepository in semgrep
> fix semgrep

- cmd/vulcan-nuclei/Dockerfile
- cmd/vulcan-nuclei/main.go
Rely on the vendor provided image equivalent to our custom image.
> base nuclei check on projectdiscovery/nuclei image

- cmd/vulcan-http-headers/Dockerfile
- cmd/vulcan-semgrep/Dockerfile
- cmd/vulcan-tls/Dockerfile
This PR is basically housekeeping, it bumps the versions of some dependencies in the DockerFiles of a few checks.
> Bump some deps

- cmd/vulcan-trivy/vulcan-trivy.go
offline scan option added to trivy check
> offline scan option

- cmd/vulcan-prowler/Dockerfile
- cmd/vulcan-prowler/cis_controls.json
- cmd/vulcan-prowler/main.go
- Pin latest compatible version for the base docker image
- Add missing control
- Avoid fail the check if a control is missing
> Fix vulcan prowler

- cmd/vulcan-semgrep/main.go
- cmd/vulcan-semgrep/manifest.toml
- cmd/vulcan-semgrep/semgrep.go
Added posiblity of config multiple rulesets and exclude rules IDs
> rules array and exclude-rule

- README.md
- cmd/vulcan-http-headers/.gitignore
- cmd/vulcan-http-headers/Dockerfile
- cmd/vulcan-http-headers/local.toml.example
- cmd/vulcan-http-headers/main.go
- cmd/vulcan-http-headers/manifest.toml
- cmd/vulcan-http-headers/observatory.go
- cmd/vulcan-http-headers/setup.py
- cmd/vulcan-http-headers/vulnerabilities.go
This reverts commit 16eae067746cdd7e263da4cd3f0eef2d5939f9f8.
> Revert "remove vulcan-http-headers (#299)"

- cmd/vulcan-nuclei/Dockerfile
- cmd/vulcan-nuclei/main.go
- cmd/vulcan-nuclei/test.sh
- upgrade nuclei
- fix breaking change in parameter -json 
- improve the test
> feat(deps): bump projectdiscovery/nuclei in /cmd/vulcan-nuclei

- cmd/vulcan-exposed-ssh/Dockerfile
- cmd/vulcan-exposed-ssh/main.go
This pr fixes the ports option being ignored
Fixes some lints
Upgrades the base image
> Update and fix vulcan-exposed-ssh
